[package]
name = "rumbac"
version = "0.1.0"
edition = "2024"
authors = ["Mateusz Czapli≈Ñski <czapkofan@gmail.com>", "ShumaTech"]
license = "GPL-3.0-or-later"

[dependencies]
anyhow = "1.0.98"
serialport = "4.7.1"
xflags = "0.3.2"
